export const SENTENCES = [
  "The quick brown fox jumps over the lazy dog.",
  "Hello world, this is a typing game.",
  "React is awesome for building UIs.",
  "Practice typing to improve your speed.",
  "Type accurately to get better results.",
  "Coding challenges help sharpen your skills.",
  "Stay consistent and you will see progress.",
  "JavaScript is a versatile programming language.",
  "Front-end development involves HTML, CSS, and JS.",
  "The user interface should be intuitive and responsive.",
  "Typing fast requires a lot of practice and patience.",
  "The weather today is sunny with a slight breeze.",
  "Keep your hands on the home row for optimal speed.",
  "Next.js is great for building React applications.",
  "Every developer should know how to debug efficiently.",
  "Dark mode is preferred by many developers at night.",
  "Web performance can affect the user experience.",
  "Write clean code so others can understand it easily.",
  "Keyboard shortcuts can boost your productivity.",
  "Always commit your code with meaningful messages.",
  "Use TypeScript to catch bugs during development.",
  "Mobile-first design is a modern web standard.",
  "A good developer never stops learning new things.",
  "Focus on quality rather than quantity in your work.",
  "Optimize images to improve loading times.",
  "Accessibility makes your site usable by everyone.",
  "Set realistic goals and track your progress daily.",
  "Time management is crucial for remote workers.",
  "Components in React should be reusable and simple.",
  "Testing your code ensures fewer production issues.",
];
